vanilla_model.ARMOR:setVisible(false)
vanilla_model.PLAYER:setVisible(false)
vanilla_model.ELYTRA:setVisible(false)
vanilla_model.HELMET_ITEM:setVisible(true)
avatar:store("hair_color",vectors.hexToRGB("#5ac54f"))
avatar:store("skin_color",vectors.hexToRGB("#2a2a2a"))